uktrade/digital-workspace

app/controllers/archive_controller.rb
app/controllers/content_controller.rb
app/models/content_queries.rb
app/views/content/index.html.haml
config/routes.rb

Hi Toby, please make this pull request

Article templates

---

app/assets/javascripts/topics.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/components/_overrides.scss
app/assets/stylesheets/components/_people-finder.scss
app/assets/stylesheets/components/_search.scss
app/assets/stylesheets/components/_typography.scss
app/assets/stylesheets/components/_zendesk.scss
app/assets/stylesheets/pages/standard/_standard-index.scss
app/assets/stylesheets/pages/topics/_topic-index.scss
app/controllers/standard_controller.rb
app/helpers/news_helper.rb
app/models/standard_queries.rb
app/views/accordion/index.html.haml
app/views/home/index.html.haml
app/views/standard/index.html.haml
app/views/topics/index.html.haml
app/views/widgets/_content_partial.html.haml
app/views/widgets/_nav.html.haml
app/views/widgets/_nav_homepage.html.haml
app/views/widgets/_people_search.html.haml
config/routes.rb

Hi Toby, can you do the honours?
Ta

Standard api

---

app/assets/javascripts/clear-inputs.js
app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/components/_search.scss

clear inputs fix

---

app/models/standard_queries.rb
app/views/layouts/application.html.haml
app/views/standard/index.html.haml

@tobyprivett all tests are green!

Standard index

---

app/assets/stylesheets/pages/accordion/_accordion.scss
app/controllers/accordion_controller.rb
app/models/accordion_queries.rb
app/views/accordion/index.html.haml

@tobyprivett can you do the honours with this branch please?

Demo fixes

---

app/controllers/standard_controller.rb

call build_global_notification

---

app/controllers/search_controller.rb

Bug where site bombed if user navigated to /search/ with no ?s query. Presence check should now have fixed that

Search pagination

---

app/assets/stylesheets/components/_header.scss
app/views/accordion/index.html.haml
app/views/archive/index.html.haml
app/views/archive/news_type.html.haml
app/views/content/content.html.haml
app/views/howdoi/content.html.haml
app/views/policy/content.html.haml
app/views/single/news.html.haml
app/views/standard/index.html.haml
app/views/topics/index.html.haml

added body classes and corresponding styles to highlight when on sections of the site

Header nav selected

---

Gemfile
Gemfile.lock
README.md
app/services/custom_health_check.rb
config/application.rb
config/initializers/health_check.rb
config/routes.rb

- Currently this page checks that People Finder, Word Press and Redis
are available
e.g. `/health_check.json`

Basic Health Check page

---

app/views/archive/news_type.html.haml
app/views/single/news.html.haml

@JordanHatch Could you do the honours please? Ta

author name

---

app/assets/stylesheets/pages/news/_news-comments.scss
app/assets/stylesheets/pages/news/_news-index.scss
app/views/home/index.html.haml
app/views/widgets/_comments.html.haml

comment box sizing and wrapping; caption styling

fixes for DW-456 and DW-427

---

app/services/custom_health_check.rb

- Here we counter any URL/path issues by checking that the route responds

Fix health check for Word Press

---

app/controllers/report_controller.rb

- The Requester field facilitates the email 
threads

Ensure Zendesk is submitted with the Requester

---

manifest.yml

Update: Migrate DW to CFv3

---

Dockerfile
Gemfile

- Allow for pry debugging in test environment
- Install `less` for better paging

Improve pry integration

---

public/500.html

More descriptive and helpful Internal Server Error page, with links to
various other places that users might want to access.

New 500 error page

---

app/models/wp_api.rb
app/views/single/news.html.haml

Changing over to use Typhoeus caused some issues due to the eccentric
use of the previous HTTP library. This fixes the issues encountered.

Resolve issues with Typhoeus change

---

app/services/custom_health_check.rb

This was failing with the new HTTP library.

Update PF health check

---

app/views/home/index.html.haml

Nobody like's greengrocer's apostrophe's.

Fix poor homepage How do I? link copy

---

app/views/widgets/_notification_bar.html.haml

Comment out the survey banner HTML, and add a placeholder comment for
future use.

Remove survey banner

---

app/assets/stylesheets/pages/home/_homepage.scss
app/views/home/_news_item.html.erb

- Make news article images clickable
- Move headline above tags/date meta info

More homepage layout changes

---

app/assets/stylesheets/components/_typography.scss
app/views/content/content.html.haml

- Remove unneeded font size overrides that broke on small screens
- Remove (one of) double rendered related content partials

Fix some visual bugs

---

app/models/twitter_api.rb

- Add ability to fetch tweets from _multiple_ users on homepage Twitter "feed"
This is more expensive than before, because the Twitter API doesn't let you fetch
tweets from more than one user in one go.
- Add Antonia's account in as an additional user
- Increase caching time to 30 minutes (instead of 1)
- Rescue Twitter API (and any other) errors so that the homepage doesn't break
when Twitter is down

Add Antonia's tweets to homepage Twitter "feed"

---

fixtures/vcr_cassettes/visit_the_landing_page/in_general.yml
fixtures/vcr_cassettes/visit_the_news_pages/in_general.yml
lib/tasks/ci.rake
test/application_system_test_case.rb
test/test_helper.rb

- Re-record VCR cassettes to fix failing build
- Ignore vulnerability in bundler audit
This vulnerability does not affect this app due to the 1-to-1 relationship
between SSO accounts and DW accounts. Unfortunately the `bundler-audit`
Rake task won't let us ignore vulnerabilities, so we need to call out
manually.
- Remove unused test folder

Miscellaneous improvements

---

config/environments/production.rb

Remove contradictory logging configuration

Logging improvements

---

.rubocop.yml
app/helpers/image_helper.rb

This removes some unnecessary exceptions and cleans up the code
further.

Final Rubocop updates

---

app/models/howdoi_query_all.rb
app/views/widgets/_content_howdois_all.html.haml

Also refactors the fetching of items.

Sort "How do I?" guides alphabetically

---

Gemfile.lock
app/assets/stylesheets/components/_related.scss
app/views/widgets/_related_content_partial.html.haml

These add no value and are just visual noise.

Remove tags from related news

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/environments/production.rb

- Standardise on same logging stack as People Finder
- Include SSO user ID with every log message

Use lograge and common DIT log format

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/single_controller.rb
app/views/widgets/_comments.html.haml
config/environments/development.rb

- Fix local development issues (we are using Redis cache store for sessions
so shouldn't disable it)

Hide comment form if news article has comments disabled

---

app/views/widgets/_people_search.html.haml

The params for People Finder search have changed and should be reflected
in this application's search form.

Update PF search field to match new params
