app/models/people_finder_profile.rb
spec/models/people_finder_profile_spec.rb

This adds a check to `PeopleFinderProfile` to catch when a response from the People Finder was not successful.
When it isn't successful, it returns an empty profile, which is consistent with the behaviour for when a profile does not exist.

Gracefully degrade when People Finder is unavailable

---

app/helpers/application_helper.rb
app/views/accordion/index.html.haml
app/views/archive/index.html.haml
app/views/archive/news_type.html.haml
app/views/layouts/application.html.haml
app/views/search/index.html.haml
app/views/single/index.html.haml
app/views/single/news.html.haml
app/views/topics/index.html.haml
app/views/widgets/_content_partial.html.haml

This changes the application layout to allow the `<title>` tag to be set by individual pages, and modifies existing content views to set the `@page_title` variable to that of the main page heading.
This approach and styling is consistent with the People Finder.

Insert the page title into the <title> tag

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_beta-bar.scss
app/assets/stylesheets/components/_beta-label.scss
app/assets/stylesheets/components/_breadcrumb.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_global-notifications.scss
app/assets/stylesheets/components/_pagination.scss
app/assets/stylesheets/components/_post-meta.scss
app/assets/stylesheets/components/_search-results.scss
app/assets/stylesheets/components/_search.scss
app/assets/stylesheets/components/_typography.scss
app/assets/stylesheets/pages/home/_homepage.scss
app/assets/stylesheets/pages/news/_news-comments.scss
app/assets/stylesheets/pages/news/_news-index.scss
app/assets/stylesheets/pages/standard/_standard-index.scss
app/assets/stylesheets/vars/_typography-sizes.scss
app/views/archive/index.html.haml
app/views/archive/news_type.html.haml

Added line-height of 1.25 for any body text that's set at 16px as per GDS, increased news excerpt sizes to small instead of xsmall, added in images to news listings. DW-424, DW-426, DW-318

A few visual tweaks to news listings and site text. 

---

app/services/custom_health_check.rb

- Here we check that the API returns the expected 'not found' error message
when searching for a person that doesn't exist
- Previously we allowed a 404 error as there was several minutes of downtime
while the deployment was running.

Improve People Finder health check

---

.travis.yml
Gemfile
Gemfile.lock
manifest.yml

The build pack now supports Ruby 2.4.4.

Update Ruby to version 2.4.4

---

app/controllers/home_controller.rb

For some reason some random front-end PR about IE8 accordions completely
deleted the backend code that populate the "How do I?" and "What's
popular?" sections on the Digital Workspace homepage:
https://github.com/uktrade/digital-workspace/pull/166
This adds the code back in (only these two sections for now). We should
evaluate why this was removed, and see whether we need to add some of
the other deleted code back in as well.

Re-add deleted "How do I?" and "What's popular" blocks

---

config/initializers/raven.rb

Errors from Digital Workspace currently show up in Sentry as coming from production regardless of whether they're from dev, staging, or production. This adds an initializer that sets the Raven environment based on the `APPLICATION_ENV` environment variable added in https://github.com/uktrade/ci-pipeline-config/pull/41

Set current Raven environment based on APPLICATION_ENV

---

config/routes.rb

On occasion, intermittent OAuth issues (most likely an weird double
redirect) can cause users to end up on `/auth/failure`, a path that
doesn't exist. The nature of these issues makes them very difficult
to debug, so we should at least make sure the user is redirected to
the homepage, instead of being sent to a 404 page by our OAuth gem.

Add redirect from non-existing OAuth error page

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/sessions_controller.rb

Workspace currently redirects non-authenticated users to the homepage
after completing the OAuth flow. That's not very helpful - they may have
followed a specific link before being sent off to log in, and
`omniauth` does provide us with a way of tracking this "origin".

Redirect to originally visited URL after OAuth flow

---

app/controllers/application_controller.rb

The recent change to redirect users after successful SSO sign in has
introduced an intermittent issue with users (apparently on IE11) being
sent to the Omniauth middleware with a bogus, seemingly ROT13-encoded
"origin" (redirect) URL.
We suspect this is an encoding issue, and this adds some rudimentary
logging around the redirect to allow us to see what is happening in
production.

Add debug log for SSO redirect

---

app/controllers/application_controller.rb

Omniauth already uses the referrer if no origin was explicitly given,
and in light of the issues we are having with ROT13'd URLs coming
through, it's an acceptable tradeoff to have users with referrer
disabled sent to the homepage instead.

Don't set Omniauth origin and rely on referrer

---

app/models/wp_api.rb

This code is messy and, like the page body request, cannot cope with
non-ASCII characters in search strings because it manually builds up
query strings.

Refactor WpApi#get_search_json_body

---

app/views/topics/index.html.haml

This header should be a more generic "Documents" rather than the
specific "Forms and templates"

Rename documents header on topic pages

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/people_finder_profile.rb
app/models/wp_api.rb
app/services/custom_health_check.rb
fixtures/vcr_cassettes/visit_the_landing_page/in_general.yml
fixtures/vcr_cassettes/visit_the_news_pages/in_general.yml
spec/models/people_finder_profile_spec.rb

Typhoeus is based on `libcurl` and allows us to work around issues with
invalid responses from Wordpress because it is more forgiving of
malformed HTTP responses (in particular the missing `Content-Length`
header we've been experiencing).
It's a drop in replacement for now, but will also allow us to perform
parallel requests and use persistent connections in the future, in order
to improve performance on some of the slowest parts of Workspace.

Use Typhoeus instead of HTTParty as HTTP library

---

app/controllers/home_controller.rb

This is implemented in the most awful way imaginable, but this commit
replicates the behaviour of the way it's done across the rest of the
application for the sake of consistency.
The notification banner is returned as an attribute on *every single
content item type* in Wordpress. Every controller fetches the first
item of content and chucks it into `@global_notification`, where the
notification partial in the application layout picks up on it. The
homepage wasn't doing that. Now it does.

Fix notification banner not showing on homepage

---

app/models/accordion_queries.rb

On the "Working at DIT" page, the individual themes only show up to a
maximum of 10 topics because of the default Wordpress fetch limit.
Never mind that these should not be one HTTP request per theme...

Increase number of topics displayed per theme

---

app/assets/stylesheets/util/_lists.scss
app/views/widgets/_content_partial.html.haml

Currently there is nothing to differentiate links to downloadable
documents in the "Documents" section from random hyperlinks.
As an MVP, this adds the GDS "file download" icon to every link in the
documents section, as well as the file size coming through from
Wordpress.

Show icon and file size for document links

---

app/assets/stylesheets/util/_lists.scss

These were a bit too close together and should be spaced further apart.

Amend margin for download link icons

---

app/views/widgets/_people_search.html.haml

It doesn't technically take you to the edit page, so the link
should say "view your profile" instead.

Change PF header link to "view"

---

app/views/widgets/_content_howdois_all.html.haml

Amends the "How do I" archive list page with the same terminology as 
used on the homepage.

Apprehend appalling apostrophe

---

app/assets/stylesheets/components/_zendesk.scss
app/views/widgets/_zendesk_footer.html.haml

One of the most common error reports received by the Digital Workspace
team is that the links on the page are not working. This is due to the
file links to S3 coming through from Wordpress as signed URLs expiring
after 15 minutes - if a users has a Digital Workspace page open in the
background for longer than that, all the links end up leading to a AWS
error page.
We cannot (easily) fix the underlying cause due to the way the Wordpress
media library offloading plugin works, and the myriad ways in which the
URLs come back from the Wordpress API, so this adds a message to the
error reporting form suggesting that if this is what the user is writing
to complain about, they should try refreshing their browser first.

Add file expiry warning to error report form

---

app/assets/stylesheets/components/_header.scss

The order of links in the header menu has changed, and since active
menu items are highlighted by position, they are now broken. This fixes
the order of items.
The Data Hub section is pointless because it's not a section - it will
still highlight "working at DIT".

Adapt header link highlighting to new menu order

---

app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/models/auth_user.rb
app/models/people_finder_profile.rb
fixtures/vcr_cassettes/visit_the_landing_page/in_general.yml
fixtures/vcr_cassettes/visit_the_news_pages/in_general.yml
lib/ditsso_internal.rb
spec/models/auth_user_spec.rb
spec/support/helpers/omniauth_helper.rb

We currently fetch user profiles from People Finder based on a user's
Omniauth email address - this should use the unique `user_id` instead.
NOTE: Deploying this will sign out all currently signed in users.

Use SSO user_id instead of email to fetch PF profile

---

app/views/home/index.html.erb

This is required for Google Tag Manager link click tracking.

Add CSS class to "quick links" <a> tags

---

app/views/archive/index.html.haml
app/views/archive/news_type.html.haml
app/views/single/news.html.haml

News articles currently fetch the names of authors from People Finder,
which is completely pointless because they come through from Wordpress
anyway. Also, this no longer works now because People Finder profiles
need to be fetched by SSO user ID.
This changes all the relevant templates to use the author name straight
from Wordpress instead.

Use WP-provided author name instead of name from PF

---

app/models/people_finder_profile.rb

The "my profile" link in the header should use the end-user facing
People Finder URL rather than the internal API URL.

Fix People Finder URL in header

---

app/controllers/application_controller.rb
app/controllers/report_controller.rb
app/controllers/sessions_controller.rb
app/models/auth_user.rb

If a user does not have a People Finder profile, their error reports
will come through as "Unknown user" without any ability to contact them.
This re-adds `email` as a property of `AuthUser`, and sends through the
user's SSO email in case they do not have a People Finder profile email
we can obtain.

Improve error reporting for users without PF profile

---

app/assets/stylesheets/pages/home/_homepage.scss
app/controllers/home_controller.rb
app/models/govuk_feed.rb
app/models/home_page_queries.rb
app/views/home/index.html.erb

This adds public-facing DIT news from DIT's GOV.UK page to the
homepage.

Add GOV.UK news from RSS feed to homepage

---

app/views/widgets/_zendesk_footer.html.haml

Now that we have a short-term fix for the 15 minute expiry on files, and
a long-term fix is in the works, we no longer need to nag users before
they submit a problem report.

Remove file expiry notice on problem report form

---

app/models/wp_response.rb

Some URLs to S3 assets are Google/MS Outlook encoded garbage and cause the
asset URL replacement regex to be excessively greedy because it doesn't
find a `=` (only `%3D`).

Improve resilience of asset URL replacement

---

app/models/wp_response.rb

We've discovered some additional forms of URL that get wrongly replaced,
escaping outside of the HTML attributes the links are contained in.
Given that no URL will contain quotes in it, this change makes sure that
any replacement will not go beyond the HTML attribute the link is
contained within.

Make asset URL replacement even less greedy

---

app/models/wp_response.rb

We've now had some occurrences of unsigned S3 URLs coming through in the
WP JSON response, which cause the giant ugly regular expression to fail.
This simplifies the search&replace to no longer use a regex looking for
URLs that look like signed S3 URLs, but instead just replace occurrences
of the S3 domain. This means it will catch non-signed S3 URLs (that lack
query parameters), but on the flip side means that signed URLs will now
have the signature query params at the end. As our proxy doesn't care
about these and will silently ignore them, this is a small price to pay
for simplifying this code and no longer having to maintain an awfully
complex regex.

Simplify asset proxy URL replacement

---

app/models/wp_response.rb

This adds the following to the exception reporting sent through Raven
when a parsing error occurs on WP's JSON response:
- URL requested
- Response HTTP status code
- Raw response body
- Response body with URLs replaced
This will help us debug issues with broken JSON coming back from WP
more effectively.

Improve error reporting for WP response parsing

---

app/assets/stylesheets/pages/standard/_standard-index.scss
app/views/standard/index.html.haml

Index pages should display when their child pages have last been updated
so that users can see at a glance if there is anything new going on.

Add last update date/time to index pages

---

docker-compose.yml

Workspace uses Docker (and Docker Compose) for local development.
This improves performance (particularly on macOS) and generally
improves the local experience by:
- Setting container volumes to delegated (which means that rather
than guaranteeing consistency all the time, Docker will consider
the container file system as authoritative and changes may take
a split second to propagate onto the host file system, which is
perfectly fine for our use case) - this massively improves IO
performance on macOS
- Making Rails write its Pidfile to /dev/null (because it rarely
managed to clean up after itself properly)

Docker performance improvements

---

app/assets/stylesheets/components/_header.scss
app/assets/stylesheets/components/_pagination.scss
app/assets/stylesheets/components/_people-finder.scss
app/assets/stylesheets/components/_related.scss
app/assets/stylesheets/pages/accordion/_accordion.scss
app/assets/stylesheets/pages/home/_homepage.scss
app/assets/stylesheets/util/_links.scss
app/assets/stylesheets/vars/_colours.scss

- Change profile bar to grey background
The transparent red background lets too much of the pattern beneath
through, leading to poor legibility
- Replace orange links with GOV.UK link colour/brand red
The orange link colour is neither on brand nor does it provide
decent contrast. This changes all links to current GOV.UK link blue
and the header "active" link to brand red
- Decrease related content link font size

Implement UX review "quick win" recommendations

---

.rubocop.yml
app/controllers/application_controller.rb
app/controllers/content_controller.rb
app/controllers/standard_controller.rb

For some reason the functionality to pick up on redirects configured in
the CMS was never implemented. This isn't great, but given the legacy
status of this app and the existing horrible state of the application,
it'll do.

Enable redirection functionality

---

app/services/custom_health_check.rb

The health check relies on behaviour in People Finder that hasn't
produced meaningful results in a long time, but a recent change
broke it completely.
- Make People Finder health check look up non-existing user by
`ditsso_user_id`, not email

Fix People Finder health check

---

app/models/people_finder_profile.rb
spec/models/people_finder_profile_spec.rb

We have changed People Finder to require a user ID being passed into the
people API, and this has unearthed that this app very frequently calls
it without one.
We need to figure out why this is happening, but until then, this stops
the API being called if there is no user ID to call it with.

Ensure PF API is not called with blank user ID

---

config/environments/production.rb

This is already enforced by our deployment pipeline but affects cookie
parameters.

Enable `force_ssl` in production

---

Gemfile
Gemfile.lock
config/environments/production.rb

We should be using the Rails built-in Redis caching integration which
makes the `readthis` gem unnecessary.
Also removes other unused gems.

Remove `readthis` and other unused gems

---

.rubocop.yml
config/application.rb
config/environments/production.rb
lib/vcap_services.rb

The URL for Redis should be read from `VCAP_SERVICES` instead of being
manually set in `REDIS_URL`.
- Add `VcapServices` helper library from People Finder
- Configure Redis through `VcapServices`

Use CloudFoundry services instead of env var for Redis URL

---

config/initializers/health_check.rb

This was still using the environment variable instead
of Rails configuration.

Health check should use correct Redis URL
